#cloud-config

coreos:
  etcd:
    # curl -w "\n" https://discovery.etcd.io/new
    discovery: https://discovery.etcd.io/7776610d4c086ec09001dbfa8ff91c49
    addr: $private_ipv4:4001
    peer-addr: $private_ipv4:7001      
  fleet:
    # used for fleetctl ssh command
    public-ip: $private_ipv4
    metadata: role=web,provider=digitalocean
  units:
    - name: etcd.service
      command: start
    - name: fleet.service
      command: start
  update:
    group: alpha
    reboot-strategy: best-effort
